-- Create enums if they don't exist
DO $$ BEGIN
  CREATE TYPE "MedicalConditionType" AS ENUM ('CHRONIC', 'ACUTE', 'CONGENITAL', 'INFECTIOUS', 'AUTOIMMUNE', 'PSYCHIATRIC', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ConditionStatus" AS ENUM ('ACTIVE', 'MANAGED', 'RESOLVED', 'IN_REMISSION');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ConditionSeverity" AS ENUM ('MILD', 'MODERATE', 'SEVERE', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ConditionSourceType" AS ENUM ('MANUAL', 'AUTO_SUGGESTED', 'IMPORTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "AllergyType" AS ENUM ('DRUG', 'FOOD', 'ENVIRONMENTAL', 'LATEX', 'INSECT', 'CONTRAST', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "AllergySeverity" AS ENUM ('MILD', 'MODERATE', 'SEVERE', 'LIFE_THREATENING');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "SmokingStatus" AS ENUM ('NEVER', 'FORMER', 'CURRENT', 'UNKNOWN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "AlcoholUseStatus" AS ENUM ('NONE', 'OCCASIONAL', 'MODERATE', 'HEAVY', 'UNKNOWN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "AppointmentPriority" AS ENUM ('ROUTINE', 'URGENT', 'EMERGENCY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "Role" AS ENUM ('DOCTOR', 'RECEPTIONIST', 'ADMIN', 'SUPER_ADMIN', 'ADMIN_DOCTOR');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER', 'INTERSEX', 'NON_BINARY', 'PREFER_NOT_TO_SAY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "CodeStatus" AS ENUM ('FULL_CODE', 'DNR', 'DNI', 'DNR_DNI', 'COMFORT_CARE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "BpPosition" AS ENUM ('SITTING', 'STANDING', 'LYING', 'UNKNOWN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "OxygenDelivery" AS ENUM ('ROOM_AIR', 'NASAL_CANNULA', 'SIMPLE_MASK', 'NON_REBREATHER', 'VENTURI_MASK', 'HIGH_FLOW', 'CPAP', 'BIPAP', 'VENTILATOR', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "BpMigrationStatus" AS ENUM ('PENDING', 'MIGRATED', 'FLAGGED', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "DosageForm" AS ENUM ('TABLET', 'CAPSULE', 'SOLUTION', 'SUSPENSION', 'INJECTION', 'CREAM', 'OINTMENT', 'GEL', 'PATCH', 'INHALER', 'NEBULIZER', 'SUPPOSITORY', 'DROPS', 'SPRAY', 'POWDER', 'LOZENGE', 'FILM', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "SigCode" AS ENUM ('QD', 'BID', 'TID', 'QID', 'Q4H', 'Q6H', 'Q8H', 'Q12H', 'QHS', 'QAM', 'QPM', 'QOD', 'QWK', 'PRN', 'STAT', 'AC', 'PC', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ConsentType" AS ENUM ('TREATMENT', 'PROCEDURE', 'SURGERY', 'ANESTHESIA', 'HIPAA_RELEASE', 'RESEARCH', 'PHOTO_VIDEO', 'TELEHEALTH', 'MINOR_GUARDIAN', 'BLOOD_TRANSFUSION', 'VACCINATION');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ConsentStatus" AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED', 'PENDING');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ImmunizationRoute" AS ENUM ('IM', 'SC', 'ID', 'PO', 'IN', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ImmunizationSite" AS ENUM ('LEFT_ARM', 'RIGHT_ARM', 'LEFT_THIGH', 'RIGHT_THIGH', 'LEFT_DELTOID', 'RIGHT_DELTOID', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "Specialization" AS ENUM ('GENERAL_PRACTICE', 'DENTAL', 'CARDIOLOGY', 'PEDIATRICS', 'OPHTHALMOLOGY', 'DERMATOLOGY', 'ORTHOPEDICS', 'NEUROLOGY', 'GYNECOLOGY', 'ENT', 'PSYCHIATRY', 'UROLOGY', 'PULMONOLOGY', 'GASTROENTEROLOGY', 'ONCOLOGY', 'NEPHROLOGY', 'ENDOCRINOLOGY', 'RHEUMATOLOGY', 'RADIOLOGY', 'PATHOLOGY', 'ANESTHESIOLOGY', 'EMERGENCY_MEDICINE', 'FAMILY_MEDICINE', 'INTERNAL_MEDICINE', 'PLASTIC_SURGERY', 'GENERAL_SURGERY', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "HospitalRole" AS ENUM ('CONSULTANT', 'SENIOR_CONSULTANT', 'JUNIOR_DOCTOR', 'RESIDENT', 'INTERN', 'VISITING_DOCTOR', 'HEAD_OF_DEPARTMENT', 'MEDICAL_DIRECTOR', 'SURGEON', 'CHIEF_SURGEON', 'ATTENDING_PHYSICIAN', 'FELLOW');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "DayOfWeek" AS ENUM ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ClinicTier" AS ENUM ('CAPTURE', 'CORE', 'PLUS', 'PRO', 'ENTERPRISE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ClinicType" AS ENUM ('GENERAL', 'DENTAL', 'SPECIALTY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "IntelligenceAddon" AS ENUM ('NONE', 'ACTIVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ImportJobType" AS ENUM ('EXCEL_PATIENTS', 'EXCEL_APPOINTMENTS', 'OCR_DOCUMENT', 'BULK_SCAN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ImportJobStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIALLY_COMPLETED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "FeedbackCategory" AS ENUM ('GENERAL', 'UI_UX', 'PERFORMANCE', 'FEATURES', 'BILLING', 'SUPPORT', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "FeedbackStatus" AS ENUM ('NEW', 'REVIEWED', 'IN_PROGRESS', 'RESOLVED', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ErrorSeverity" AS ENUM ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "MetricType" AS ENUM ('CPU_USAGE', 'MEMORY_USAGE', 'HEAP_USED', 'HEAP_TOTAL', 'ACTIVE_CONNECTIONS', 'DB_QUERY_TIME', 'UPTIME', 'REQUEST_COUNT', 'ERROR_RATE', 'AVG_RESPONSE_TIME');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "SubscriptionStatus" AS ENUM ('ACTIVE', 'TRIALING', 'PAST_DUE', 'GRACE', 'CANCELLED', 'EXPIRED', 'PAUSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "BillingCycle" AS ENUM ('MONTHLY', 'YEARLY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ReferralStatus" AS ENUM ('PENDING', 'SIGNED_UP', 'CONVERTED', 'REJECTED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Add the type column to Clinic table if it doesn't exist
ALTER TABLE "Clinic" ADD COLUMN IF NOT EXISTS "type" "ClinicType" NOT NULL DEFAULT 'GENERAL';

-- Add consultationNotes column to Appointment if it doesn't exist
ALTER TABLE "Appointment" ADD COLUMN IF NOT EXISTS "consultationNotes" TEXT;
